### PR TITLE
Allocate space for "Other Settings" button proportionally to the translation lengt

### PR DESCRIPTION
**Pull request by kobliha**
- bsc#946955
- New screenshots are at https://trello.com/c/OrH3F8uW/348-2-sle12-sp1-p1-946955-yast-date-and-time-not-enough-space-for-button

### CODE REVIEW

**Comment by lslezak** [comment]
:warning:  On the Czech screenshots the end of the checkbox label for the UCT switch is missing...

**Comment by shundhammer** [comment]
The approach to fix those layout constraints is a bit unusual, but it's a workaround to a known UI limitation (no grid layout available).

LGTM.

**Comment by kobliha** [comment]
@lslezak See new screenshots, CZ fixed, the rest still fits ;)

**Comment by lslezak** [comment]
LGTM, thanks! :+1:

**Comment by kobliha** [comment]
@lslezak @shundhammer thanks for review :)

**Pull request merged**
