### PR TITLE
Asturian keyboard support

### PR DESCRIPTION
**Pull request by ancorgs**

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM, we should get rid of that ycp data files

**Comment by mvidner** [comment]
@ancorgs Does this depend on a feature added only recently to an underlying package? If yes, then we should note it in the changelog. (A RPM dependency is not appropriate)

**Comment by ancorgs** [comment]
@mvidner I believe support for Asturian has been in the underlying system since we adopted systemd. It was only missing in YaST, AFAIK.

**Comment by mvidner** [comment]
OK, somehow I got the impression that we were waiting for an updated package. If not, fine.
LGTM

**Pull request merged**
